"""empty message

Revision ID: 9d3e2f1a6b7c
Revises: b7f2c8a1d9a4
Create Date: 2026-04-30 12:00:00.000000

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from langboard_shared.core.db.ColumnTypes import CSVType, SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "9d3e2f1a6b7c"
down_revision: Union[str, None] = "b7f2c8a1d9a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_schedule_rule",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_str", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("recipients", CSVType(str), nullable=False),
        sa.Column("repeat_after_hours", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_schedule_rule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_schedule_rule_field"), ["field"], unique=False)
        batch_op.create_index(batch_op.f("ix_notification_schedule_rule_is_enabled"), ["is_enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_notification_schedule_rule_operator"), ["operator"], unique=False)
        batch_op.create_index(batch_op.f("ix_notification_schedule_rule_target"), ["target"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_schedule_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_schedule_rule_target"))
        batch_op.drop_index(batch_op.f("ix_notification_schedule_rule_operator"))
        batch_op.drop_index(batch_op.f("ix_notification_schedule_rule_is_enabled"))
        batch_op.drop_index(batch_op.f("ix_notification_schedule_rule_field"))

    op.drop_table("notification_schedule_rule")
    # ### end Alembic commands ###
