"""empty message

Revision ID: 28862ce390a1
Revises: 321365839046
Create Date: 2026-06-11 02:14:28.616222

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from langboard_shared.core.db.ColumnTypes import EnumLikeType, SnowflakeIDType
from langboard_shared.domain.models.GraphApprovalRequest import GraphApprovalRequestType, GraphApprovalStatus


# revision identifiers, used by Alembic.
revision: str = "28862ce390a1"
down_revision: Union[str, None] = "321365839046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_approval_request",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("requested_by_user_id", SnowflakeIDType, nullable=True),
        sa.Column("resolved_by_user_id", SnowflakeIDType, nullable=True),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("request_type", EnumLikeType(GraphApprovalRequestType), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column("api_name", sa.String(), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("preview_payload", sa.JSON(), nullable=False),
        sa.Column("status", EnumLikeType(GraphApprovalStatus), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_approval_request")),
    )
    with op.batch_alter_table("graph_approval_request", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_graph_approval_request_api_name"), ["api_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_approval_request_permission"), ["permission"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_approval_request_request_type"), ["request_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_graph_approval_request_requested_by_user_id"), ["requested_by_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_graph_approval_request_resolved_by_user_id"), ["resolved_by_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_graph_approval_request_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_approval_request_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_graph_approval_request_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "editor_graph_approval_request",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("approval_request_id", SnowflakeIDType, nullable=False),
        sa.Column("scope_table", sa.String(), nullable=False),
        sa.Column("scope_id", SnowflakeIDType, nullable=True),
        sa.Column("document_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["graph_approval_request.id"],
            name=op.f("fk_editor_graph_approval_request_approval_request_id_graph_approval_request"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_editor_graph_approval_request")),
    )
    with op.batch_alter_table("editor_graph_approval_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_editor_graph_approval_request_approval_request_id"), ["approval_request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_editor_graph_approval_request_document_name"), ["document_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_editor_graph_approval_request_scope_id"), ["scope_id"], unique=False)

    op.create_table(
        "bot_schedule_graph_approval_request",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("approval_request_id", SnowflakeIDType, nullable=False),
        sa.Column("scope_table", sa.String(), nullable=False),
        sa.Column("scope_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_id", SnowflakeIDType, nullable=True),
        sa.Column("internal_bot_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_log_id", SnowflakeIDType, nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["graph_approval_request.id"],
            name=op.f("fk_bot_schedule_graph_approval_request_approval_request_id_graph_approval_request"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bot.id"], name=op.f("fk_bot_schedule_graph_approval_request_bot_id_bot"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["bot_log_id"],
            ["bot_log.id"],
            name=op.f("fk_bot_schedule_graph_approval_request_bot_log_id_bot_log"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["internal_bot_id"],
            ["internal_bot.id"],
            name=op.f("fk_bot_schedule_graph_approval_request_internal_bot_id_internal_bot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_schedule_graph_approval_request")),
    )
    with op.batch_alter_table("bot_schedule_graph_approval_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_schedule_graph_approval_request_approval_request_id"),
            ["approval_request_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_bot_schedule_graph_approval_request_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_bot_schedule_graph_approval_request_bot_log_id"), ["bot_log_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bot_schedule_graph_approval_request_internal_bot_id"), ["internal_bot_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bot_schedule_graph_approval_request_scope_id"), ["scope_id"], unique=False)

    op.create_table(
        "bot_trigger_graph_approval_request",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("approval_request_id", SnowflakeIDType, nullable=False),
        sa.Column("scope_table", sa.String(), nullable=False),
        sa.Column("scope_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_id", SnowflakeIDType, nullable=True),
        sa.Column("internal_bot_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_log_id", SnowflakeIDType, nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["graph_approval_request.id"],
            name=op.f("fk_bot_trigger_graph_approval_request_approval_request_id_graph_approval_request"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bot.id"], name=op.f("fk_bot_trigger_graph_approval_request_bot_id_bot"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["bot_log_id"],
            ["bot_log.id"],
            name=op.f("fk_bot_trigger_graph_approval_request_bot_log_id_bot_log"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["internal_bot_id"],
            ["internal_bot.id"],
            name=op.f("fk_bot_trigger_graph_approval_request_internal_bot_id_internal_bot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_trigger_graph_approval_request")),
    )
    with op.batch_alter_table("bot_trigger_graph_approval_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_trigger_graph_approval_request_approval_request_id"),
            ["approval_request_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_bot_trigger_graph_approval_request_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_bot_trigger_graph_approval_request_bot_log_id"), ["bot_log_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bot_trigger_graph_approval_request_internal_bot_id"), ["internal_bot_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bot_trigger_graph_approval_request_scope_id"), ["scope_id"], unique=False)

    op.create_table(
        "manual_scope_run_graph_approval_request",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("approval_request_id", SnowflakeIDType, nullable=False),
        sa.Column("scope_table", sa.String(), nullable=False),
        sa.Column("scope_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_id", SnowflakeIDType, nullable=True),
        sa.Column("internal_bot_id", SnowflakeIDType, nullable=True),
        sa.Column("bot_log_id", SnowflakeIDType, nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["graph_approval_request.id"],
            name=op.f("fk_manual_scope_run_graph_approval_request_approval_request_id_graph_approval_request"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bot.id"],
            name=op.f("fk_manual_scope_run_graph_approval_request_bot_id_bot"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["bot_log_id"],
            ["bot_log.id"],
            name=op.f("fk_manual_scope_run_graph_approval_request_bot_log_id_bot_log"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["internal_bot_id"],
            ["internal_bot.id"],
            name=op.f("fk_manual_scope_run_graph_approval_request_internal_bot_id_internal_bot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_scope_run_graph_approval_request")),
    )
    with op.batch_alter_table("manual_scope_run_graph_approval_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_manual_scope_run_graph_approval_request_approval_request_id"),
            ["approval_request_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_manual_scope_run_graph_approval_request_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_manual_scope_run_graph_approval_request_bot_log_id"), ["bot_log_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_manual_scope_run_graph_approval_request_internal_bot_id"), ["internal_bot_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_manual_scope_run_graph_approval_request_scope_id"), ["scope_id"], unique=False
        )

    op.create_table(
        "chat_graph_approval_request",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("approval_request_id", SnowflakeIDType, nullable=False),
        sa.Column("scope_table", sa.String(), nullable=False),
        sa.Column("scope_id", SnowflakeIDType, nullable=True),
        sa.Column("chat_session_id", SnowflakeIDType, nullable=False),
        sa.Column("chat_history_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["graph_approval_request.id"],
            name=op.f("fk_chat_graph_approval_request_approval_request_id_graph_approval_request"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_history_id"],
            ["chat_history.id"],
            name=op.f("fk_chat_graph_approval_request_chat_history_id_chat_history"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chat_session_id"],
            ["chat_session.id"],
            name=op.f("fk_chat_graph_approval_request_chat_session_id_chat_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_graph_approval_request")),
    )
    with op.batch_alter_table("chat_graph_approval_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_graph_approval_request_approval_request_id"), ["approval_request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_graph_approval_request_chat_history_id"), ["chat_history_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_graph_approval_request_chat_session_id"), ["chat_session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chat_graph_approval_request_scope_id"), ["scope_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_graph_approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_graph_approval_request_scope_id"))
        batch_op.drop_index(batch_op.f("ix_chat_graph_approval_request_chat_session_id"))
        batch_op.drop_index(batch_op.f("ix_chat_graph_approval_request_chat_history_id"))
        batch_op.drop_index(batch_op.f("ix_chat_graph_approval_request_approval_request_id"))

    op.drop_table("chat_graph_approval_request")
    with op.batch_alter_table("manual_scope_run_graph_approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manual_scope_run_graph_approval_request_scope_id"))
        batch_op.drop_index(batch_op.f("ix_manual_scope_run_graph_approval_request_internal_bot_id"))
        batch_op.drop_index(batch_op.f("ix_manual_scope_run_graph_approval_request_bot_log_id"))
        batch_op.drop_index(batch_op.f("ix_manual_scope_run_graph_approval_request_bot_id"))
        batch_op.drop_index(batch_op.f("ix_manual_scope_run_graph_approval_request_approval_request_id"))

    op.drop_table("manual_scope_run_graph_approval_request")
    with op.batch_alter_table("bot_trigger_graph_approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_trigger_graph_approval_request_scope_id"))
        batch_op.drop_index(batch_op.f("ix_bot_trigger_graph_approval_request_internal_bot_id"))
        batch_op.drop_index(batch_op.f("ix_bot_trigger_graph_approval_request_bot_log_id"))
        batch_op.drop_index(batch_op.f("ix_bot_trigger_graph_approval_request_bot_id"))
        batch_op.drop_index(batch_op.f("ix_bot_trigger_graph_approval_request_approval_request_id"))

    op.drop_table("bot_trigger_graph_approval_request")
    with op.batch_alter_table("bot_schedule_graph_approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_schedule_graph_approval_request_scope_id"))
        batch_op.drop_index(batch_op.f("ix_bot_schedule_graph_approval_request_internal_bot_id"))
        batch_op.drop_index(batch_op.f("ix_bot_schedule_graph_approval_request_bot_log_id"))
        batch_op.drop_index(batch_op.f("ix_bot_schedule_graph_approval_request_bot_id"))
        batch_op.drop_index(batch_op.f("ix_bot_schedule_graph_approval_request_approval_request_id"))

    op.drop_table("bot_schedule_graph_approval_request")
    with op.batch_alter_table("editor_graph_approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_editor_graph_approval_request_scope_id"))
        batch_op.drop_index(batch_op.f("ix_editor_graph_approval_request_document_name"))
        batch_op.drop_index(batch_op.f("ix_editor_graph_approval_request_approval_request_id"))

    op.drop_table("editor_graph_approval_request")
    with op.batch_alter_table("graph_approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_thread_id"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_status"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_run_id"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_resolved_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_requested_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_request_type"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_permission"))
        batch_op.drop_index(batch_op.f("ix_graph_approval_request_api_name"))

    op.drop_table("graph_approval_request")
    # ### end Alembic commands ###
