"""empty message

Revision ID: b432b0dbaaaf
Revises: 9d3e2f1a6b7c
Create Date: 2026-05-13 09:04:54.350668

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b432b0dbaaaf"
down_revision: Union[str, None] = "9d3e2f1a6b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkitem", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkitem", schema=None) as batch_op:
        batch_op.drop_column("deadline_at")

    # ### end Alembic commands ###
