"""empty message

Revision ID: 321365839046
Revises: 42520b49d47f
Create Date: 2026-06-08 06:07:16.573486

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "321365839046"
down_revision: Union[str, None] = "42520b49d47f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in ("project_bot_scope", "project_column_bot_scope", "card_bot_scope"):
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.add_column(sa.Column("is_frozen", sa.Boolean(), server_default=sa.false(), nullable=False))
            batch_op.alter_column("is_frozen", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in ("card_bot_scope", "project_column_bot_scope", "project_bot_scope"):
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.drop_column("is_frozen")
    # ### end Alembic commands ###
