"""add project user relationship history

Revision ID: 09fd3bc91042
Revises: e5db18e78261
Create Date: 2026-06-15 05:20:02.742304

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "09fd3bc91042"
down_revision: Union[str, None] = "e5db18e78261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_user_relationship",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("project_id", SnowflakeIDType, nullable=False),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.Column("related_user_id", SnowflakeIDType, nullable=False),
        sa.Column("last_related_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_user_relationship_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["related_user_id"],
            ["user.id"],
            name=op.f("fk_project_user_relationship_related_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_project_user_relationship_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_user_relationship")),
        sa.UniqueConstraint(
            "project_id", "user_id", "related_user_id", name="uq_project_user_relationship_project_user_related_user"
        ),
    )
    op.create_index(
        op.f("ix_project_user_relationship_project_id"), "project_user_relationship", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_user_relationship_related_user_id"),
        "project_user_relationship",
        ["related_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_user_relationship_user_id"), "project_user_relationship", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_user_relationship_user_id"), table_name="project_user_relationship")
    op.drop_index(op.f("ix_project_user_relationship_related_user_id"), table_name="project_user_relationship")
    op.drop_index(op.f("ix_project_user_relationship_project_id"), table_name="project_user_relationship")
    op.drop_table("project_user_relationship")
    # ### end Alembic commands ###
