"""empty message

Revision ID: e5db18e78261
Revises: 28862ce390a1
Create Date: 2026-06-12 04:05:51.710084

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e5db18e78261"
down_revision: Union[str, None] = "28862ce390a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_permission_level", sa.String(), server_default="read", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.drop_column("api_permission_level")

    # ### end Alembic commands ###
