"""empty message

Revision ID: 42520b49d47f
Revises: b432b0dbaaaf
Create Date: 2026-06-05 07:17:42.025778

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "42520b49d47f"
down_revision: Union[str, None] = "b432b0dbaaaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scim_group",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scim_group")),
        sa.UniqueConstraint("external_id", name=op.f("uq_scim_group_external_id")),
    )
    op.create_index(op.f("ix_scim_group_display_name"), "scim_group", ["display_name"], unique=False)
    op.create_index(op.f("ix_scim_group_external_id"), "scim_group", ["external_id"], unique=True)
    op.create_table(
        "scim_group_member",
        sa.Column("id", SnowflakeIDType, autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("group_id", SnowflakeIDType, nullable=False),
        sa.Column("user_id", SnowflakeIDType, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["scim_group.id"], name=op.f("fk_scim_group_member_group_id_scim_group"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_scim_group_member_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scim_group_member")),
        sa.UniqueConstraint("group_id", "user_id", name="uq_scim_group_member_group_user"),
    )
    op.create_index(op.f("ix_scim_group_member_group_id"), "scim_group_member", ["group_id"], unique=False)
    op.create_index(op.f("ix_scim_group_member_user_id"), "scim_group_member", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scim_group_member_user_id"), table_name="scim_group_member")
    op.drop_index(op.f("ix_scim_group_member_group_id"), table_name="scim_group_member")
    op.drop_table("scim_group_member")
    op.drop_index(op.f("ix_scim_group_external_id"), table_name="scim_group")
    op.drop_index(op.f("ix_scim_group_display_name"), table_name="scim_group")
    op.drop_table("scim_group")
    # ### end Alembic commands ###
