"""empty message

Revision ID: b432b0dbaaaf
Revises: 9d3e2f1a6b7c
Create Date: 2026-05-13 09:04:54.350668

"""

from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from langboard_shared.core.db.ColumnTypes import CSVType, SnowflakeIDType


# revision identifiers, used by Alembic.
revision: str = "b432b0dbaaaf"
down_revision: Union[str, None] = "9d3e2f1a6b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_comfort_tool",
        sa.Column("id", SnowflakeIDType, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("api_names", CSVType(str), nullable=False),
        sa.Column("query", sa.JSON(), nullable=False),
        sa.Column("form", sa.JSON(), nullable=False),
        sa.Column("api_queries", sa.JSON(), nullable=False),
        sa.Column("api_forms", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("api_comfort_tool", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_comfort_tool_name"), ["name"], unique=True)

    with op.batch_alter_table("checkitem", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkitem", schema=None) as batch_op:
        batch_op.drop_column("deadline_at")

    with op.batch_alter_table("api_comfort_tool", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_comfort_tool_name"))

    op.drop_table("api_comfort_tool")

    # ### end Alembic commands ###
